# Generated by Django 5.0.3 on 2024-04-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField(max_length=12)),
                ('DOB', models.DateField()),
                ('Medical_Id', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Specialty', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=30)),
                ('Profile', models.ImageField(upload_to='images')),
            ],
        ),
    ]
