# Generated by Django 5.0.3 on 2024-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_doctor_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Doctor_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
