# Generated by Django 5.0.3 on 2024-04-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctor_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='permanent',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
