# Generated by Django 5.0.3 on 2024-04-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctor_permanent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Email', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=200)),
                ('Contact', models.CharField(max_length=14)),
                ('Disease', models.CharField(max_length=200)),
                ('Blood_Group', models.CharField(max_length=4)),
                ('Doctor', models.CharField(max_length=200)),
                ('Patient_id', models.CharField(default='', max_length=10)),
                ('appointed', models.CharField(default='False', max_length=5)),
                ('Date', models.CharField(default='False', max_length=5)),
            ],
        ),
    ]
