# Generated by Django 5.0.3 on 2024-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Date',
            field=models.CharField(default='False', max_length=15),
        ),
    ]
