# Generated by Django 5.0.3 on 2024-04-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_patient_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admittd',
            field=models.CharField(default='False', max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='checked',
            field=models.CharField(default='False', max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharged',
            field=models.CharField(default='False', max_length=6),
        ),
    ]
