# Generated by Django 5.0.3 on 2024-04-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_patient_admittd_patient_checked_patient_discharged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='admittd',
            new_name='admitted',
        ),
    ]
