# Generated by Django 5.0.3 on 2024-04-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_admittd_patient_admitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='admitPatients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_id', models.CharField(default='', max_length=10)),
                ('Date', models.DateField()),
                ('time', models.TimeField()),
                ('Bed_no', models.IntegerField()),
            ],
        ),
    ]
