# Generated by Django 5.0.3 on 2024-04-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_admitpatients'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Gender',
            field=models.CharField(default='', max_length=7),
        ),
    ]
