# Generated by Django 5.0.3 on 2024-04-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_admitpatients_bed_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitpatients',
            name='Doctor_id',
            field=models.CharField(default='', max_length=12),
        ),
    ]
