# Generated by Django 5.0.3 on 2024-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_admitpatients_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
