# Generated by Django 5.0.3 on 2024-04-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
