# Generated by Django 5.0.3 on 2024-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_feedback_date_alter_feedback_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Date',
            field=models.CharField(default='', max_length=15),
        ),
    ]
