# Generated by Django 5.0.3 on 2024-04-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Address',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
