# Generated by Django 5.0.3 on 2024-04-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_feedback_email_alter_feedback_message_and_more'),
        ('app', '0019_alter_patient_address'),
    ]

    operations = [
    ]
