# Generated by Django 5.0.3 on 2024-04-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_merge_20240417_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Join',
            field=models.CharField(default='', max_length=11),
        ),
    ]
