# Generated by Django 5.0.3 on 2024-04-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
