# Generated by Django 5.0.3 on 2024-04-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_bill_day_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Day_spent',
            field=models.IntegerField(default=0),
        ),
    ]
