# Generated by Django 5.0.3 on 2024-04-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_bill_day_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Salary',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
