# Generated by Django 5.0.3 on 2024-05-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_doctor_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
