# Generated by Django 5.0.3 on 2024-05-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_doctor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Join',
            field=models.CharField(default='---', max_length=11),
        ),
    ]
