# Generated by Django 5.0.3 on 2024-05-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_doctor_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
