# Generated by Django 5.0.3 on 2024-05-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Date',
            field=models.CharField(default='---', max_length=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='Paid',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
