# Generated by Django 5.0.3 on 2024-05-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_bill_date_bill_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='Day_spent',
        ),
        migrations.AlterField(
            model_name='bill',
            name='Room_charges',
            field=models.IntegerField(default=1200),
        ),
    ]
